version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: elegant_bartik
    environment:
      MYSQL_ROOT_PASSWORD:   # Senha do root
      MYSQL_DATABASE: stock_db        # Nome do banco de dados
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql        # Para persistir os dados do banco
    networks:
      - springboot-network

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile    # Referencia o Dockerfile para a aplicação Spring Boot
    container_name: springboot-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stock_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge

volumes:
  mysql-data:
